# Generated by Django 5.2 on 2025-06-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_alter_run_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('INIT', 'init'), ('WIP', 'in_progress'), ('DONE', 'finished')], default='INIT', max_length=4),
        ),
    ]
